//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMONIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public int ID { get; set; }
        public int IDUser { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogutTime { get; set; }
        public string Reason { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
